Se desarrollo el componente y pagina de Special Kit
FooCamp/atalaya pull request #16
Opened 2022-11-04 04:37 UTC by JulianaMorenoj

2022-11-04 11:15 UTC, victoralfonsoperez requested changes
En términos generales se ve bien
hay un par de cambios que son necesarios para evitar conflictos con otros estilos
Una recomendación adicional es que el Pull Request debe contener información suficiente para darle contexto a quien lo revisa, ej: imagenes de los cambios visuales, instrucciones de cómo probar esos cambios, etc.

2022-11-04 11:15 UTC, victoralfonsoperez commented on src/scss/components/specialkit.scss
> +h2 {
Recuerda que estos estilos aplica a todos los elementos h2 de la página, lo mismo para los parrafos abajo
Por especificidad lo mejor es generar nombres de clases dentro del ámbito del componente
ej: 
.componente {
&--titulo{
// estilos especificos para el titulo del componente
}
}

2022-11-04 11:15 UTC, victoralfonsoperez commented on src/scss/components/specialkit.scss
> +#content-special-kit {
En general no se usa mucho aplicar estilos mediante identificadores, mejor usar clases para ello.

2022-11-04 11:15 UTC, victoralfonsoperez commented on src/scss/components/specialkit.scss
> +  background-image: var(--fondo-sk);
Buen detalle de pasar el fondo como una variable.

2022-11-04 23:16 UTC, JulianaMorenoj commented on src/scss/components/specialkit.scss
> +  background-image: var(--fondo-sk);
Adjunto evidencias de los cambios realizados:  

Se ajusto el componente productos y paragragh, se cambiaron los identificadores por clases y se creo una funcion para el currency en pesos colombianos

Uploading Special Kit - Google Chrome 2022-11-04 17-59-56.mp4…

 
https://user-images.githubusercontent.com/113148352/200087479-e65bf828-b22b-4aa0-b601-75694cf9b977.mp4

2022-11-04 23:17 UTC, JulianaMorenoj commented on src/scss/components/specialkit.scss
> +  background-image: var(--fondo-sk);
https://user-images.githubusercontent.com/113148352/200088055-1afe1fff-b536-473c-bc96-14e5101173bf.mp4

2022-11-09 01:01 UTC, tibecvp approved these changes
Revisé los cambios con los comentarios de @victoralfonsoperez. No tengo comentarios adicionales.

2022-11-10 15:28 UTC, victoralfonsoperez approved these changes

2022-11-10 15:31 UTC, merged